#pragma once
// Auto-generated by the Protocol Modeling tool. Do not edit manually.
#include <array>
#include <cstddef>
#include <cstdint>
#include <cstring>
// #include "MB_DDF/Tools/SelfDescribingLog.h" — 已移除

namespace ProtocolModel {

struct Helm_ins_frame {
    uint8_t head1; // 帧头1 / 非解析字段
    uint8_t head2; // 帧头2 / 非解析字段
    uint8_t length; // 帧长 / 非解析字段
    uint16_t serial_a; // 流水号
    float Q; // 动压
    double temp_imu; // 惯测温度
    double temp_ground; // 地面温度
    float ins[4]; // 舵指令
    uint8_t plug_detach; // 拖插分离
    uint8_t check1; // 校验1 / 非解析字段
    uint8_t check2; // 校验2 / 非解析字段

    // Initialize fields with default values.
    Helm_ins_frame() {
        head1 = 170;
        head2 = 85;
        length = 27;
        serial_a = 0;
        Q = 0;
        temp_imu = 30;
        temp_ground = 30;
        ins[0] = 0;
        ins[1] = 0;
        ins[2] = 0;
        ins[3] = 0;
        plug_detach = 0;
        check1 = 0;
        check2 = 0;
    }
};

class Helm_ins_frameProtocol {
public:
    constexpr static size_t FRAME_SIZE = 27;

    // Return byte offset of a member within the frame struct.
    template<typename T, typename Member>
    constexpr static uint32_t offset_of_member(Member T::*member_ptr) {
        return static_cast<uint32_t>(
            reinterpret_cast<uintptr_t>(
                &(static_cast<T*>(nullptr)->*member_ptr)
            )
        );
    }

    // Write 16-bit unsigned integer in little-endian.
    static inline void writeLe16(char* dst, uint16_t value) {
        dst[0] = static_cast<char>(value & 0xFF);
        dst[1] = static_cast<char>((value >> 8) & 0xFF);
    }

    // Write 32-bit unsigned integer in little-endian.
    static inline void writeLe32(char* dst, uint32_t value) {
        dst[0] = static_cast<char>(value & 0xFF);
        dst[1] = static_cast<char>((value >> 8) & 0xFF);
        dst[2] = static_cast<char>((value >> 16) & 0xFF);
        dst[3] = static_cast<char>((value >> 24) & 0xFF);
    }

    // Read 16-bit unsigned integer in little-endian.
    static inline uint16_t readLe16(const char* src) {
        return static_cast<uint8_t>(src[0]) | (static_cast<uint8_t>(src[1]) << 8);
    }

    // Read 32-bit unsigned integer in little-endian.
    static inline uint32_t readLe32(const char* src) {
        return static_cast<uint8_t>(src[0]) | (static_cast<uint8_t>(src[1]) << 8)
            | (static_cast<uint8_t>(src[2]) << 16) | (static_cast<uint8_t>(src[3]) << 24);
    }

    // Encode unsigned value with LSB scaling.
    static inline uint32_t encodeUnsigned(double actual, double lsb) {
        return static_cast<uint32_t>(actual / lsb);
    }

    // Encode signed value with LSB scaling.
    static inline int32_t encodeSigned(double actual, double lsb) {
        return static_cast<int32_t>(actual / lsb);
    }

    // Decode unsigned value with LSB scaling.
    static inline double decodeUnsigned(uint32_t encoded, double lsb) {
        return static_cast<double>(encoded) * lsb;
    }

    // Decode signed value with LSB scaling.
    static inline double decodeSigned(int32_t encoded, double lsb) {
        return static_cast<double>(encoded) * lsb;
    }

    // Pack valid fields into a byte buffer.
    static std::array<char, FRAME_SIZE> packFrame(const Helm_ins_frame& frame) {
        std::array<char, FRAME_SIZE> buffer{};
        writeLe16(buffer.data() + 0, static_cast<uint16_t>(frame.serial_a));
        {
            float value = static_cast<float>(frame.Q);
            uint32_t raw = 0;
            std::memcpy(&raw, &value, sizeof(raw));
            writeLe32(buffer.data() + 2, raw);
        }
        writeLe16(buffer.data() + 6, static_cast<uint16_t>(encodeSigned(frame.temp_imu, 0.1)));
        writeLe16(buffer.data() + 8, static_cast<uint16_t>(encodeSigned(frame.temp_ground, 0.1)));
        {
            float value = static_cast<float>(frame.ins[0]);
            uint32_t raw = 0;
            std::memcpy(&raw, &value, sizeof(raw));
            writeLe32(buffer.data() + 10, raw);
        }
        {
            float value = static_cast<float>(frame.ins[1]);
            uint32_t raw = 0;
            std::memcpy(&raw, &value, sizeof(raw));
            writeLe32(buffer.data() + 14, raw);
        }
        {
            float value = static_cast<float>(frame.ins[2]);
            uint32_t raw = 0;
            std::memcpy(&raw, &value, sizeof(raw));
            writeLe32(buffer.data() + 18, raw);
        }
        {
            float value = static_cast<float>(frame.ins[3]);
            uint32_t raw = 0;
            std::memcpy(&raw, &value, sizeof(raw));
            writeLe32(buffer.data() + 22, raw);
        }
        buffer[26] = static_cast<char>(frame.plug_detach);
        return buffer;
    }

    // Unpack valid fields from a byte buffer.
    static bool unpackFrame(const char* rawData, size_t dataSize, Helm_ins_frame& frame) {
        if ((!rawData) || (dataSize < FRAME_SIZE)) {
            return false;
        }
        frame.serial_a = readLe16(rawData + 0);
        {
            uint32_t raw = readLe32(rawData + 2);
            float value = 0.0f;
            std::memcpy(&value, &raw, sizeof(value));
            frame.Q = value;
        }
        frame.temp_imu = decodeSigned(static_cast<int16_t>(readLe16(rawData + 6)), 0.1);
        frame.temp_ground = decodeSigned(static_cast<int16_t>(readLe16(rawData + 8)), 0.1);
        {
            uint32_t raw = readLe32(rawData + 10);
            float value = 0.0f;
            std::memcpy(&value, &raw, sizeof(value));
            frame.ins[0] = value;
        }
        {
            uint32_t raw = readLe32(rawData + 14);
            float value = 0.0f;
            std::memcpy(&value, &raw, sizeof(value));
            frame.ins[1] = value;
        }
        {
            uint32_t raw = readLe32(rawData + 18);
            float value = 0.0f;
            std::memcpy(&value, &raw, sizeof(value));
            frame.ins[2] = value;
        }
        {
            uint32_t raw = readLe32(rawData + 22);
            float value = 0.0f;
            std::memcpy(&value, &raw, sizeof(value));
            frame.ins[3] = value;
        }
        frame.plug_detach = static_cast<uint8_t>(rawData[26]);
        return true;
    }

    // buildSchema() 已移除（SelfDescribingLog 模块已废弃）
};

} // namespace ProtocolModel
