#pragma once
// Auto-generated by the Protocol Modeling tool. Do not edit manually.
#include <array>
#include <cstddef>
#include <cstdint>
#include <cstring>
// #include "MB_DDF/Tools/SelfDescribingLog.h" — 已移除

namespace ProtocolModel {

struct Helm_fdb_frame {
    struct BitGroup1 {
        uint16_t self_check : 2; // 电气自检
        uint16_t bit1 : 2; // 舵自检1
        uint16_t bit2 : 2; // 舵自检2
        uint16_t bit3 : 2; // 舵自检3
        uint16_t bit4 : 2; // 舵自检4
        uint16_t bit : 2; // 舵自检合
    };
    uint8_t head1; // 帧头1 / 非解析字段
    uint8_t head2; // 帧头2 / 非解析字段
    uint8_t length; // 帧长 / 非解析字段
    uint16_t serial_b; // 流水号b
    uint16_t version; // 版本号
    float fdb[4]; // 舵反馈
    BitGroup1 bitGroup1;
    uint8_t timeout; // 超时标识
    uint16_t serial_a; // 流水号a
    float ins[4]; // 舵指令
    uint8_t check1; // 校验1 / 非解析字段
    uint8_t check2; // 校验2 / 非解析字段

    // Initialize fields with default values.
    Helm_fdb_frame() {
        head1 = 85;
        head2 = 165;
        length = 41;
        serial_b = 0;
        version = 16384;
        fdb[0] = 0;
        fdb[1] = 0;
        fdb[2] = 0;
        fdb[3] = 0;
        bitGroup1.self_check = 0;
        bitGroup1.bit1 = 0;
        bitGroup1.bit2 = 0;
        bitGroup1.bit3 = 0;
        bitGroup1.bit4 = 0;
        bitGroup1.bit = 0;
        timeout = 0;
        serial_a = 0;
        ins[0] = 0;
        ins[1] = 0;
        ins[2] = 0;
        ins[3] = 0;
        check1 = 0;
        check2 = 0;
    }
};

class Helm_fdb_frameProtocol {
public:
    constexpr static size_t FRAME_SIZE = 41;

    // Return byte offset of a member within the frame struct.
    template<typename T, typename Member>
    constexpr static uint32_t offset_of_member(Member T::*member_ptr) {
        return static_cast<uint32_t>(
            reinterpret_cast<uintptr_t>(
                &(static_cast<T*>(nullptr)->*member_ptr)
            )
        );
    }

    // Write 16-bit unsigned integer in little-endian.
    static inline void writeLe16(char* dst, uint16_t value) {
        dst[0] = static_cast<char>(value & 0xFF);
        dst[1] = static_cast<char>((value >> 8) & 0xFF);
    }

    // Write 32-bit unsigned integer in little-endian.
    static inline void writeLe32(char* dst, uint32_t value) {
        dst[0] = static_cast<char>(value & 0xFF);
        dst[1] = static_cast<char>((value >> 8) & 0xFF);
        dst[2] = static_cast<char>((value >> 16) & 0xFF);
        dst[3] = static_cast<char>((value >> 24) & 0xFF);
    }

    // Read 16-bit unsigned integer in little-endian.
    static inline uint16_t readLe16(const char* src) {
        return static_cast<uint8_t>(src[0]) | (static_cast<uint8_t>(src[1]) << 8);
    }

    // Read 32-bit unsigned integer in little-endian.
    static inline uint32_t readLe32(const char* src) {
        return static_cast<uint8_t>(src[0]) | (static_cast<uint8_t>(src[1]) << 8)
            | (static_cast<uint8_t>(src[2]) << 16) | (static_cast<uint8_t>(src[3]) << 24);
    }

    // Encode unsigned value with LSB scaling.
    static inline uint32_t encodeUnsigned(double actual, double lsb) {
        return static_cast<uint32_t>(actual / lsb);
    }

    // Encode signed value with LSB scaling.
    static inline int32_t encodeSigned(double actual, double lsb) {
        return static_cast<int32_t>(actual / lsb);
    }

    // Decode unsigned value with LSB scaling.
    static inline double decodeUnsigned(uint32_t encoded, double lsb) {
        return static_cast<double>(encoded) * lsb;
    }

    // Decode signed value with LSB scaling.
    static inline double decodeSigned(int32_t encoded, double lsb) {
        return static_cast<double>(encoded) * lsb;
    }

    // Pack valid fields into a byte buffer.
    static std::array<char, FRAME_SIZE> packFrame(const Helm_fdb_frame& frame) {
        std::array<char, FRAME_SIZE> buffer{};
        writeLe16(buffer.data() + 0, static_cast<uint16_t>(frame.serial_b));
        writeLe16(buffer.data() + 2, static_cast<uint16_t>(frame.version));
        {
            float value = static_cast<float>(frame.fdb[0]);
            uint32_t raw = 0;
            std::memcpy(&raw, &value, sizeof(raw));
            writeLe32(buffer.data() + 4, raw);
        }
        {
            float value = static_cast<float>(frame.fdb[1]);
            uint32_t raw = 0;
            std::memcpy(&raw, &value, sizeof(raw));
            writeLe32(buffer.data() + 8, raw);
        }
        {
            float value = static_cast<float>(frame.fdb[2]);
            uint32_t raw = 0;
            std::memcpy(&raw, &value, sizeof(raw));
            writeLe32(buffer.data() + 12, raw);
        }
        {
            float value = static_cast<float>(frame.fdb[3]);
            uint32_t raw = 0;
            std::memcpy(&raw, &value, sizeof(raw));
            writeLe32(buffer.data() + 16, raw);
        }
        uint16_t bitGroup1Value = 0;
        bitGroup1Value |= (static_cast<uint16_t>(frame.bitGroup1.self_check) & ((1u << 2) - 1u)) << 0;
        bitGroup1Value |= (static_cast<uint16_t>(frame.bitGroup1.bit1) & ((1u << 2) - 1u)) << 2;
        bitGroup1Value |= (static_cast<uint16_t>(frame.bitGroup1.bit2) & ((1u << 2) - 1u)) << 4;
        bitGroup1Value |= (static_cast<uint16_t>(frame.bitGroup1.bit3) & ((1u << 2) - 1u)) << 6;
        bitGroup1Value |= (static_cast<uint16_t>(frame.bitGroup1.bit4) & ((1u << 2) - 1u)) << 8;
        bitGroup1Value |= (static_cast<uint16_t>(frame.bitGroup1.bit) & ((1u << 2) - 1u)) << 10;
        writeLe16(buffer.data() + 20, bitGroup1Value);
        buffer[22] = static_cast<char>(frame.timeout);
        writeLe16(buffer.data() + 23, static_cast<uint16_t>(frame.serial_a));
        {
            float value = static_cast<float>(frame.ins[0]);
            uint32_t raw = 0;
            std::memcpy(&raw, &value, sizeof(raw));
            writeLe32(buffer.data() + 25, raw);
        }
        {
            float value = static_cast<float>(frame.ins[1]);
            uint32_t raw = 0;
            std::memcpy(&raw, &value, sizeof(raw));
            writeLe32(buffer.data() + 29, raw);
        }
        {
            float value = static_cast<float>(frame.ins[2]);
            uint32_t raw = 0;
            std::memcpy(&raw, &value, sizeof(raw));
            writeLe32(buffer.data() + 33, raw);
        }
        {
            float value = static_cast<float>(frame.ins[3]);
            uint32_t raw = 0;
            std::memcpy(&raw, &value, sizeof(raw));
            writeLe32(buffer.data() + 37, raw);
        }
        return buffer;
    }

    // Unpack valid fields from a byte buffer.
    static bool unpackFrame(const char* rawData, size_t dataSize, Helm_fdb_frame& frame) {
        if ((!rawData) || (dataSize < FRAME_SIZE)) {
            return false;
        }
        frame.serial_b = readLe16(rawData + 0);
        frame.version = readLe16(rawData + 2);
        {
            uint32_t raw = readLe32(rawData + 4);
            float value = 0.0f;
            std::memcpy(&value, &raw, sizeof(value));
            frame.fdb[0] = value;
        }
        {
            uint32_t raw = readLe32(rawData + 8);
            float value = 0.0f;
            std::memcpy(&value, &raw, sizeof(value));
            frame.fdb[1] = value;
        }
        {
            uint32_t raw = readLe32(rawData + 12);
            float value = 0.0f;
            std::memcpy(&value, &raw, sizeof(value));
            frame.fdb[2] = value;
        }
        {
            uint32_t raw = readLe32(rawData + 16);
            float value = 0.0f;
            std::memcpy(&value, &raw, sizeof(value));
            frame.fdb[3] = value;
        }
        uint16_t bitGroup1Value = readLe16(rawData + 20);
        frame.bitGroup1.self_check = (bitGroup1Value >> 0) & ((1u << 2) - 1u);
        frame.bitGroup1.bit1 = (bitGroup1Value >> 2) & ((1u << 2) - 1u);
        frame.bitGroup1.bit2 = (bitGroup1Value >> 4) & ((1u << 2) - 1u);
        frame.bitGroup1.bit3 = (bitGroup1Value >> 6) & ((1u << 2) - 1u);
        frame.bitGroup1.bit4 = (bitGroup1Value >> 8) & ((1u << 2) - 1u);
        frame.bitGroup1.bit = (bitGroup1Value >> 10) & ((1u << 2) - 1u);
        frame.timeout = static_cast<uint8_t>(rawData[22]);
        frame.serial_a = readLe16(rawData + 23);
        {
            uint32_t raw = readLe32(rawData + 25);
            float value = 0.0f;
            std::memcpy(&value, &raw, sizeof(value));
            frame.ins[0] = value;
        }
        {
            uint32_t raw = readLe32(rawData + 29);
            float value = 0.0f;
            std::memcpy(&value, &raw, sizeof(value));
            frame.ins[1] = value;
        }
        {
            uint32_t raw = readLe32(rawData + 33);
            float value = 0.0f;
            std::memcpy(&value, &raw, sizeof(value));
            frame.ins[2] = value;
        }
        {
            uint32_t raw = readLe32(rawData + 37);
            float value = 0.0f;
            std::memcpy(&value, &raw, sizeof(value));
            frame.ins[3] = value;
        }
        return true;
    }

    // buildSchema() 已移除（SelfDescribingLog 模块已废弃）
};

} // namespace ProtocolModel
