#pragma once
// Auto-generated by the Protocol Modeling tool. Do not edit manually.
#include <array>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include "MB_DDF/Tools/SelfDescribingLog.h"

namespace ProtocolModel {

struct Dyt_to_main_frame_b {
    struct DespunInsStatus {
        uint8_t calibrationStatus : 2; // 消旋惯测标定状态
        uint8_t softwareStatus : 2; // 消旋惯测软件状态
        uint8_t reservedBits : 4; // 备份
    };
    struct DytStatus {
        uint8_t selfTestStatus : 2; // DYT自检状态
        uint8_t acquisitionStatus : 2; // DYT截获状态
        uint8_t operatingStatus : 2; // DYT工作状态
        uint8_t operatingModeFeedback : 2; // DYT工作模式回告
    };
    struct SelfTestFlags {
        uint16_t innerEncoderSelfTest : 1; // 内框码盘自检状态
        uint16_t outerEncoderSelfTest : 1; // 外框码盘自检状态
        uint16_t despunEncoderSelfTest : 1; // 消旋码盘自检状态
        uint16_t gimbalGyroSelfTest : 1; // 框架陀螺自检状态
        uint16_t insSelfTest : 1; // 惯组自检状态
        uint16_t imageSelfTest : 1; // 图像自检状态
        uint16_t communication422SelfTest : 1; // 422通讯自检状态
        uint16_t gimbalSelfTest : 1; // 框架自检状态
        uint16_t innerEncoderHoming : 1; // 内框码盘寻零状态
        uint16_t outerEncoderHoming : 1; // 外框码盘寻零状态
        uint16_t despunEncoderHoming : 1; // 消旋码盘寻零状态
        uint16_t operatingSystemSelfTest : 1; // 操作系统自检
        uint16_t imageStorageStatus : 1; // 图像存储状态
        uint16_t reservedBits : 3; // 备份
    };
    struct ControlStatus {
        uint8_t gimbalControlStatus : 4; // 框架控制状态
        uint8_t despunControlStatus : 4; // 消旋控制状态
    };
    struct ImageControl {
        uint16_t programmedGear : 4; // 程控档位
        uint16_t imageCaptureMode : 4; // 图像截获模式
        uint16_t losAngularVelocityAvailable : 1; // 视线角速度可用状态
        uint16_t angleMeasurementAvailable : 1; // 测角可用状态
        uint16_t imageCalibrationStatus : 2; // 图像校正状态
        uint16_t reservedBits : 4; // 备份
    };
    uint8_t frameHeaderLow; // B帧帧头低字节 / 非解析字段
    uint8_t frameHeaderHigh; // B帧帧头高字节 / 非解析字段
    uint8_t frameLength; // B帧帧长 / 非解析字段
    uint8_t frameIdentifier; // B帧帧标识
    uint16_t frameCounter; // B帧帧计数
    double despunEncoderRollAngle; // 消旋码盘滚转角度
    double despunPlatformRollAngle; // 消旋平台滚转角（惯测积分）
    double spinFrequency; // 弹旋频率
    uint8_t despunInsSequence; // 消旋惯测序列号
    double despunInsAngleIncrementX; // 消旋惯测X轴角增量Δαx
    double despunInsAngleIncrementY; // 消旋惯测Y轴角增量Δαy
    double despunInsAngleIncrementZ; // 消旋惯测Z轴角增量Δαz
    double despunInsVelocityIncrementX; // 消旋惯测X轴速度增量ΔVx
    double despunInsVelocityIncrementY; // 消旋惯测Y轴速度增量ΔVy
    double despunInsVelocityIncrementZ; // 消旋惯测Z轴速度增量ΔVz
    double despunInsAngularVelocityX; // 消旋惯测X轴角速度ωx
    double despunInsAngularVelocityY; // 消旋惯测Y轴角速度ωy
    double despunInsAngularVelocityZ; // 消旋惯测Z轴角速度ωz
    double despunInsAccelerationX; // 消旋惯测X轴加速度Nx
    double despunInsAccelerationY; // 消旋惯测Y轴加速度Ny
    double despunInsAccelerationZ; // 消旋惯测Z轴加速度Nz
    int8_t despunInsTemperature; // 消旋惯测温度T
    uint16_t despunInsSelfTestStatus; // 消旋惯测自检分状态
    DespunInsStatus despunInsStatus;
    uint16_t despunInsSoftwareVersion; // 消旋惯测软件版本号
    double innerEncoderAngleYaw; // 内框码盘角度（偏航）
    double outerEncoderAnglePitch; // 外框码盘角度（俯仰）
    double innerLosAngularVelocityDespun; // 内框视线角速度dqh（消旋）
    double outerLosAngularVelocityDespun; // 外框视线角速度dqv（消旋）
    double innerLosAngularVelocityBody; // 内框视线角速度dqh（弹体系）
    double outerLosAngularVelocityBody; // 外框视线角速度dqv（弹体系）
    DytStatus dytStatus;
    double innerGyroAngularVelocity; // 内框陀螺角速度
    double outerGyroAngularVelocity; // 外框陀螺角速度
    double innerMotorVoltage; // 内框电机电压
    double outerMotorVoltage; // 外框电机电压
    double despunMotorVoltage; // 消旋电机电压
    double pitchAngleDespun; // 俯仰测角（消旋系）
    double yawAngleDespun; // 偏航测角（消旋系）
    double pitchAngleBody; // 俯仰测角（弹体系）
    double yawAngleBody; // 偏航测角（弹体系）
    int8_t gyroTemperature; // 陀螺温度
    SelfTestFlags selfTestFlags;
    uint8_t imageSelfTestStatus; // 图像自检状态
    ControlStatus controlStatus;
    double targetErrorAngleX; // 目标误差角ΔX
    double targetErrorAngleY; // 目标误差角ΔY
    ImageControl imageControl;
    uint16_t targetGrayscaleMean; // 目标灰度均值
    uint16_t fullImageMean; // 全图均值
    uint8_t innerEncoderCommunicationError; // 内框码盘通讯误码
    uint8_t outerEncoderCommunicationError; // 外框码盘通讯误码
    uint8_t despunEncoderCommunicationError; // 消旋码盘通讯误码
    uint8_t gyroCommunicationError; // 陀螺通讯误码
    uint8_t insCommunicationError; // 惯组通讯误码
    uint8_t communication422Error; // 422通讯误码
    uint8_t imageRv1126bCommunicationError; // 图像RV1126B通讯误码
    std::array<uint8_t, 2> reserved96_97{}; // 备份
    uint16_t checksum; // B帧校验 / 非解析字段

    // Initialize fields with default values.
    Dyt_to_main_frame_b() {
        frameHeaderLow = 85;
        frameHeaderHigh = 170;
        frameLength = 95;
        frameIdentifier = 160;
        frameCounter = 0;
        despunEncoderRollAngle = 0;
        despunPlatformRollAngle = 0;
        spinFrequency = 0;
        despunInsSequence = 0;
        despunInsAngleIncrementX = 0;
        despunInsAngleIncrementY = 0;
        despunInsAngleIncrementZ = 0;
        despunInsVelocityIncrementX = 0;
        despunInsVelocityIncrementY = 0;
        despunInsVelocityIncrementZ = 0;
        despunInsAngularVelocityX = 0;
        despunInsAngularVelocityY = 0;
        despunInsAngularVelocityZ = 0;
        despunInsAccelerationX = 0;
        despunInsAccelerationY = 0;
        despunInsAccelerationZ = 0;
        despunInsTemperature = 0;
        despunInsSelfTestStatus = 0;
        despunInsStatus.calibrationStatus = 0;
        despunInsStatus.softwareStatus = 0;
        despunInsStatus.reservedBits = 0;
        innerEncoderAngleYaw = 0;
        outerEncoderAnglePitch = 0;
        innerLosAngularVelocityDespun = 0;
        outerLosAngularVelocityDespun = 0;
        innerLosAngularVelocityBody = 0;
        outerLosAngularVelocityBody = 0;
        dytStatus.selfTestStatus = 0;
        dytStatus.acquisitionStatus = 0;
        dytStatus.operatingStatus = 0;
        dytStatus.operatingModeFeedback = 0;
        innerGyroAngularVelocity = 0;
        outerGyroAngularVelocity = 0;
        innerMotorVoltage = 0;
        outerMotorVoltage = 0;
        despunMotorVoltage = 0;
        pitchAngleDespun = 0;
        yawAngleDespun = 0;
        pitchAngleBody = 0;
        yawAngleBody = 0;
        gyroTemperature = 0;
        selfTestFlags.innerEncoderSelfTest = 0;
        selfTestFlags.outerEncoderSelfTest = 0;
        selfTestFlags.despunEncoderSelfTest = 0;
        selfTestFlags.gimbalGyroSelfTest = 0;
        selfTestFlags.insSelfTest = 0;
        selfTestFlags.imageSelfTest = 0;
        selfTestFlags.communication422SelfTest = 0;
        selfTestFlags.gimbalSelfTest = 0;
        selfTestFlags.innerEncoderHoming = 0;
        selfTestFlags.outerEncoderHoming = 0;
        selfTestFlags.despunEncoderHoming = 0;
        selfTestFlags.operatingSystemSelfTest = 0;
        selfTestFlags.imageStorageStatus = 0;
        selfTestFlags.reservedBits = 0;
        imageSelfTestStatus = 0;
        controlStatus.gimbalControlStatus = 0;
        controlStatus.despunControlStatus = 0;
        targetErrorAngleX = 0;
        targetErrorAngleY = 0;
        imageControl.programmedGear = 0;
        imageControl.imageCaptureMode = 0;
        imageControl.losAngularVelocityAvailable = 0;
        imageControl.angleMeasurementAvailable = 0;
        imageControl.imageCalibrationStatus = 0;
        imageControl.reservedBits = 0;
        targetGrayscaleMean = 0;
        fullImageMean = 0;
        innerEncoderCommunicationError = 0;
        outerEncoderCommunicationError = 0;
        despunEncoderCommunicationError = 0;
        gyroCommunicationError = 0;
        insCommunicationError = 0;
        communication422Error = 0;
        imageRv1126bCommunicationError = 0;
        checksum = 0;
    }
};

class Dyt_to_main_frame_bProtocol {
public:
    constexpr static size_t FRAME_SIZE = 95;

    // Return byte offset of a member within the frame struct.
    template<typename T, typename Member>
    constexpr static uint32_t offset_of_member(Member T::*member_ptr) {
        return static_cast<uint32_t>(
            reinterpret_cast<uintptr_t>(
                &(static_cast<T*>(nullptr)->*member_ptr)
            )
        );
    }

    // Write 16-bit unsigned integer in little-endian.
    static inline void writeLe16(char* dst, uint16_t value) {
        dst[0] = static_cast<char>(value & 0xFF);
        dst[1] = static_cast<char>((value >> 8) & 0xFF);
    }

    // Write 32-bit unsigned integer in little-endian.
    static inline void writeLe32(char* dst, uint32_t value) {
        dst[0] = static_cast<char>(value & 0xFF);
        dst[1] = static_cast<char>((value >> 8) & 0xFF);
        dst[2] = static_cast<char>((value >> 16) & 0xFF);
        dst[3] = static_cast<char>((value >> 24) & 0xFF);
    }

    // Read 16-bit unsigned integer in little-endian.
    static inline uint16_t readLe16(const char* src) {
        return static_cast<uint8_t>(src[0]) | (static_cast<uint8_t>(src[1]) << 8);
    }

    // Read 32-bit unsigned integer in little-endian.
    static inline uint32_t readLe32(const char* src) {
        return static_cast<uint8_t>(src[0]) | (static_cast<uint8_t>(src[1]) << 8)
            | (static_cast<uint8_t>(src[2]) << 16) | (static_cast<uint8_t>(src[3]) << 24);
    }

    // Encode unsigned value with LSB scaling.
    static inline uint32_t encodeUnsigned(double actual, double lsb) {
        return static_cast<uint32_t>(actual / lsb);
    }

    // Encode signed value with LSB scaling.
    static inline int32_t encodeSigned(double actual, double lsb) {
        return static_cast<int32_t>(actual / lsb);
    }

    // Decode unsigned value with LSB scaling.
    static inline double decodeUnsigned(uint32_t encoded, double lsb) {
        return static_cast<double>(encoded) * lsb;
    }

    // Decode signed value with LSB scaling.
    static inline double decodeSigned(int32_t encoded, double lsb) {
        return static_cast<double>(encoded) * lsb;
    }

    // Pack valid fields into a byte buffer.
    static std::array<char, FRAME_SIZE> packFrame(const Dyt_to_main_frame_b& frame) {
        std::array<char, FRAME_SIZE> buffer{};
        buffer[0] = static_cast<char>(frame.frameIdentifier);
        writeLe16(buffer.data() + 1, static_cast<uint16_t>(frame.frameCounter));
        writeLe16(buffer.data() + 3, static_cast<uint16_t>(encodeSigned(frame.despunEncoderRollAngle, 0.0055)));
        writeLe16(buffer.data() + 5, static_cast<uint16_t>(encodeSigned(frame.despunPlatformRollAngle, 0.0055)));
        writeLe16(buffer.data() + 7, static_cast<uint16_t>(encodeUnsigned(frame.spinFrequency, 0.000306)));
        buffer[9] = static_cast<char>(frame.despunInsSequence);
        writeLe16(buffer.data() + 10, static_cast<uint16_t>(encodeSigned(frame.despunInsAngleIncrementX, 6.1038e-05)));
        writeLe16(buffer.data() + 12, static_cast<uint16_t>(encodeSigned(frame.despunInsAngleIncrementY, 6.1038e-05)));
        writeLe16(buffer.data() + 14, static_cast<uint16_t>(encodeSigned(frame.despunInsAngleIncrementZ, 6.1038e-05)));
        writeLe16(buffer.data() + 16, static_cast<uint16_t>(encodeSigned(frame.despunInsVelocityIncrementX, 0.00010682)));
        writeLe16(buffer.data() + 18, static_cast<uint16_t>(encodeSigned(frame.despunInsVelocityIncrementY, 3.815e-05)));
        writeLe16(buffer.data() + 20, static_cast<uint16_t>(encodeSigned(frame.despunInsVelocityIncrementZ, 3.815e-05)));
        writeLe16(buffer.data() + 22, static_cast<uint16_t>(encodeSigned(frame.despunInsAngularVelocityX, 0.0246)));
        writeLe16(buffer.data() + 24, static_cast<uint16_t>(encodeSigned(frame.despunInsAngularVelocityY, 0.0246)));
        writeLe16(buffer.data() + 26, static_cast<uint16_t>(encodeSigned(frame.despunInsAngularVelocityZ, 0.0246)));
        writeLe16(buffer.data() + 28, static_cast<uint16_t>(encodeSigned(frame.despunInsAccelerationX, 0.044)));
        writeLe16(buffer.data() + 30, static_cast<uint16_t>(encodeSigned(frame.despunInsAccelerationY, 0.0155)));
        writeLe16(buffer.data() + 32, static_cast<uint16_t>(encodeSigned(frame.despunInsAccelerationZ, 0.0155)));
        buffer[34] = static_cast<char>(frame.despunInsTemperature);
        writeLe16(buffer.data() + 35, static_cast<uint16_t>(frame.despunInsSelfTestStatus));
        uint8_t despunInsStatusValue = 0;
        despunInsStatusValue |= (static_cast<uint8_t>(frame.despunInsStatus.calibrationStatus) & ((1u << 2) - 1u)) << 0;
        despunInsStatusValue |= (static_cast<uint8_t>(frame.despunInsStatus.softwareStatus) & ((1u << 2) - 1u)) << 2;
        despunInsStatusValue |= (static_cast<uint8_t>(frame.despunInsStatus.reservedBits) & ((1u << 4) - 1u)) << 4;
        buffer[37] = static_cast<char>(despunInsStatusValue);
        writeLe16(buffer.data() + 38, static_cast<uint16_t>(frame.despunInsSoftwareVersion));
        writeLe16(buffer.data() + 40, static_cast<uint16_t>(encodeSigned(frame.innerEncoderAngleYaw, 0.002)));
        writeLe16(buffer.data() + 42, static_cast<uint16_t>(encodeSigned(frame.outerEncoderAnglePitch, 0.002)));
        writeLe16(buffer.data() + 44, static_cast<uint16_t>(encodeSigned(frame.innerLosAngularVelocityDespun, 0.002)));
        writeLe16(buffer.data() + 46, static_cast<uint16_t>(encodeSigned(frame.outerLosAngularVelocityDespun, 0.002)));
        writeLe16(buffer.data() + 48, static_cast<uint16_t>(encodeSigned(frame.innerLosAngularVelocityBody, 0.002)));
        writeLe16(buffer.data() + 50, static_cast<uint16_t>(encodeSigned(frame.outerLosAngularVelocityBody, 0.002)));
        uint8_t dytStatusValue = 0;
        dytStatusValue |= (static_cast<uint8_t>(frame.dytStatus.selfTestStatus) & ((1u << 2) - 1u)) << 0;
        dytStatusValue |= (static_cast<uint8_t>(frame.dytStatus.acquisitionStatus) & ((1u << 2) - 1u)) << 2;
        dytStatusValue |= (static_cast<uint8_t>(frame.dytStatus.operatingStatus) & ((1u << 2) - 1u)) << 4;
        dytStatusValue |= (static_cast<uint8_t>(frame.dytStatus.operatingModeFeedback) & ((1u << 2) - 1u)) << 6;
        buffer[52] = static_cast<char>(dytStatusValue);
        writeLe16(buffer.data() + 53, static_cast<uint16_t>(encodeSigned(frame.innerGyroAngularVelocity, 0.0077)));
        writeLe16(buffer.data() + 55, static_cast<uint16_t>(encodeSigned(frame.outerGyroAngularVelocity, 0.0077)));
        writeLe16(buffer.data() + 57, static_cast<uint16_t>(encodeSigned(frame.innerMotorVoltage, 0.00125)));
        writeLe16(buffer.data() + 59, static_cast<uint16_t>(encodeSigned(frame.outerMotorVoltage, 0.00125)));
        writeLe16(buffer.data() + 61, static_cast<uint16_t>(encodeSigned(frame.despunMotorVoltage, 0.00087)));
        writeLe16(buffer.data() + 63, static_cast<uint16_t>(encodeSigned(frame.pitchAngleDespun, 0.002)));
        writeLe16(buffer.data() + 65, static_cast<uint16_t>(encodeSigned(frame.yawAngleDespun, 0.002)));
        writeLe16(buffer.data() + 67, static_cast<uint16_t>(encodeSigned(frame.pitchAngleBody, 0.002)));
        writeLe16(buffer.data() + 69, static_cast<uint16_t>(encodeSigned(frame.yawAngleBody, 0.002)));
        buffer[71] = static_cast<char>(frame.gyroTemperature);
        uint16_t selfTestFlagsValue = 0;
        selfTestFlagsValue |= (static_cast<uint16_t>(frame.selfTestFlags.innerEncoderSelfTest) & ((1u << 1) - 1u)) << 0;
        selfTestFlagsValue |= (static_cast<uint16_t>(frame.selfTestFlags.outerEncoderSelfTest) & ((1u << 1) - 1u)) << 1;
        selfTestFlagsValue |= (static_cast<uint16_t>(frame.selfTestFlags.despunEncoderSelfTest) & ((1u << 1) - 1u)) << 2;
        selfTestFlagsValue |= (static_cast<uint16_t>(frame.selfTestFlags.gimbalGyroSelfTest) & ((1u << 1) - 1u)) << 3;
        selfTestFlagsValue |= (static_cast<uint16_t>(frame.selfTestFlags.insSelfTest) & ((1u << 1) - 1u)) << 4;
        selfTestFlagsValue |= (static_cast<uint16_t>(frame.selfTestFlags.imageSelfTest) & ((1u << 1) - 1u)) << 5;
        selfTestFlagsValue |= (static_cast<uint16_t>(frame.selfTestFlags.communication422SelfTest) & ((1u << 1) - 1u)) << 6;
        selfTestFlagsValue |= (static_cast<uint16_t>(frame.selfTestFlags.gimbalSelfTest) & ((1u << 1) - 1u)) << 7;
        selfTestFlagsValue |= (static_cast<uint16_t>(frame.selfTestFlags.innerEncoderHoming) & ((1u << 1) - 1u)) << 8;
        selfTestFlagsValue |= (static_cast<uint16_t>(frame.selfTestFlags.outerEncoderHoming) & ((1u << 1) - 1u)) << 9;
        selfTestFlagsValue |= (static_cast<uint16_t>(frame.selfTestFlags.despunEncoderHoming) & ((1u << 1) - 1u)) << 10;
        selfTestFlagsValue |= (static_cast<uint16_t>(frame.selfTestFlags.operatingSystemSelfTest) & ((1u << 1) - 1u)) << 11;
        selfTestFlagsValue |= (static_cast<uint16_t>(frame.selfTestFlags.imageStorageStatus) & ((1u << 1) - 1u)) << 12;
        selfTestFlagsValue |= (static_cast<uint16_t>(frame.selfTestFlags.reservedBits) & ((1u << 3) - 1u)) << 13;
        writeLe16(buffer.data() + 72, selfTestFlagsValue);
        buffer[74] = static_cast<char>(frame.imageSelfTestStatus);
        uint8_t controlStatusValue = 0;
        controlStatusValue |= (static_cast<uint8_t>(frame.controlStatus.gimbalControlStatus) & ((1u << 4) - 1u)) << 0;
        controlStatusValue |= (static_cast<uint8_t>(frame.controlStatus.despunControlStatus) & ((1u << 4) - 1u)) << 4;
        buffer[75] = static_cast<char>(controlStatusValue);
        writeLe16(buffer.data() + 76, static_cast<uint16_t>(encodeSigned(frame.targetErrorAngleX, 0.1)));
        writeLe16(buffer.data() + 78, static_cast<uint16_t>(encodeSigned(frame.targetErrorAngleY, 0.1)));
        uint16_t imageControlValue = 0;
        imageControlValue |= (static_cast<uint16_t>(frame.imageControl.programmedGear) & ((1u << 4) - 1u)) << 0;
        imageControlValue |= (static_cast<uint16_t>(frame.imageControl.imageCaptureMode) & ((1u << 4) - 1u)) << 4;
        imageControlValue |= (static_cast<uint16_t>(frame.imageControl.losAngularVelocityAvailable) & ((1u << 1) - 1u)) << 8;
        imageControlValue |= (static_cast<uint16_t>(frame.imageControl.angleMeasurementAvailable) & ((1u << 1) - 1u)) << 9;
        imageControlValue |= (static_cast<uint16_t>(frame.imageControl.imageCalibrationStatus) & ((1u << 2) - 1u)) << 10;
        imageControlValue |= (static_cast<uint16_t>(frame.imageControl.reservedBits) & ((1u << 4) - 1u)) << 12;
        writeLe16(buffer.data() + 80, imageControlValue);
        writeLe16(buffer.data() + 82, static_cast<uint16_t>(frame.targetGrayscaleMean));
        writeLe16(buffer.data() + 84, static_cast<uint16_t>(frame.fullImageMean));
        buffer[86] = static_cast<char>(frame.innerEncoderCommunicationError);
        buffer[87] = static_cast<char>(frame.outerEncoderCommunicationError);
        buffer[88] = static_cast<char>(frame.despunEncoderCommunicationError);
        buffer[89] = static_cast<char>(frame.gyroCommunicationError);
        buffer[90] = static_cast<char>(frame.insCommunicationError);
        buffer[91] = static_cast<char>(frame.communication422Error);
        buffer[92] = static_cast<char>(frame.imageRv1126bCommunicationError);
        return buffer;
    }

    // Unpack valid fields from a byte buffer.
    static bool unpackFrame(const char* rawData, size_t dataSize, Dyt_to_main_frame_b& frame) {
        if ((!rawData) || (dataSize < FRAME_SIZE)) {
            return false;
        }
        frame.frameIdentifier = static_cast<uint8_t>(rawData[0]);
        frame.frameCounter = readLe16(rawData + 1);
        frame.despunEncoderRollAngle = decodeSigned(static_cast<int16_t>(readLe16(rawData + 3)), 0.0055);
        frame.despunPlatformRollAngle = decodeSigned(static_cast<int16_t>(readLe16(rawData + 5)), 0.0055);
        frame.spinFrequency = decodeUnsigned(readLe16(rawData + 7), 0.000306);
        frame.despunInsSequence = static_cast<uint8_t>(rawData[9]);
        frame.despunInsAngleIncrementX = decodeSigned(static_cast<int16_t>(readLe16(rawData + 10)), 6.1038e-05);
        frame.despunInsAngleIncrementY = decodeSigned(static_cast<int16_t>(readLe16(rawData + 12)), 6.1038e-05);
        frame.despunInsAngleIncrementZ = decodeSigned(static_cast<int16_t>(readLe16(rawData + 14)), 6.1038e-05);
        frame.despunInsVelocityIncrementX = decodeSigned(static_cast<int16_t>(readLe16(rawData + 16)), 0.00010682);
        frame.despunInsVelocityIncrementY = decodeSigned(static_cast<int16_t>(readLe16(rawData + 18)), 3.815e-05);
        frame.despunInsVelocityIncrementZ = decodeSigned(static_cast<int16_t>(readLe16(rawData + 20)), 3.815e-05);
        frame.despunInsAngularVelocityX = decodeSigned(static_cast<int16_t>(readLe16(rawData + 22)), 0.0246);
        frame.despunInsAngularVelocityY = decodeSigned(static_cast<int16_t>(readLe16(rawData + 24)), 0.0246);
        frame.despunInsAngularVelocityZ = decodeSigned(static_cast<int16_t>(readLe16(rawData + 26)), 0.0246);
        frame.despunInsAccelerationX = decodeSigned(static_cast<int16_t>(readLe16(rawData + 28)), 0.044);
        frame.despunInsAccelerationY = decodeSigned(static_cast<int16_t>(readLe16(rawData + 30)), 0.0155);
        frame.despunInsAccelerationZ = decodeSigned(static_cast<int16_t>(readLe16(rawData + 32)), 0.0155);
        frame.despunInsTemperature = static_cast<int8_t>(rawData[34]);
        frame.despunInsSelfTestStatus = readLe16(rawData + 35);
        uint8_t despunInsStatusValue = static_cast<uint8_t>(rawData[37]);
        frame.despunInsStatus.calibrationStatus = (despunInsStatusValue >> 0) & ((1u << 2) - 1u);
        frame.despunInsStatus.softwareStatus = (despunInsStatusValue >> 2) & ((1u << 2) - 1u);
        frame.despunInsStatus.reservedBits = (despunInsStatusValue >> 4) & ((1u << 4) - 1u);
        frame.despunInsSoftwareVersion = readLe16(rawData + 38);
        frame.innerEncoderAngleYaw = decodeSigned(static_cast<int16_t>(readLe16(rawData + 40)), 0.002);
        frame.outerEncoderAnglePitch = decodeSigned(static_cast<int16_t>(readLe16(rawData + 42)), 0.002);
        frame.innerLosAngularVelocityDespun = decodeSigned(static_cast<int16_t>(readLe16(rawData + 44)), 0.002);
        frame.outerLosAngularVelocityDespun = decodeSigned(static_cast<int16_t>(readLe16(rawData + 46)), 0.002);
        frame.innerLosAngularVelocityBody = decodeSigned(static_cast<int16_t>(readLe16(rawData + 48)), 0.002);
        frame.outerLosAngularVelocityBody = decodeSigned(static_cast<int16_t>(readLe16(rawData + 50)), 0.002);
        uint8_t dytStatusValue = static_cast<uint8_t>(rawData[52]);
        frame.dytStatus.selfTestStatus = (dytStatusValue >> 0) & ((1u << 2) - 1u);
        frame.dytStatus.acquisitionStatus = (dytStatusValue >> 2) & ((1u << 2) - 1u);
        frame.dytStatus.operatingStatus = (dytStatusValue >> 4) & ((1u << 2) - 1u);
        frame.dytStatus.operatingModeFeedback = (dytStatusValue >> 6) & ((1u << 2) - 1u);
        frame.innerGyroAngularVelocity = decodeSigned(static_cast<int16_t>(readLe16(rawData + 53)), 0.0077);
        frame.outerGyroAngularVelocity = decodeSigned(static_cast<int16_t>(readLe16(rawData + 55)), 0.0077);
        frame.innerMotorVoltage = decodeSigned(static_cast<int16_t>(readLe16(rawData + 57)), 0.00125);
        frame.outerMotorVoltage = decodeSigned(static_cast<int16_t>(readLe16(rawData + 59)), 0.00125);
        frame.despunMotorVoltage = decodeSigned(static_cast<int16_t>(readLe16(rawData + 61)), 0.00087);
        frame.pitchAngleDespun = decodeSigned(static_cast<int16_t>(readLe16(rawData + 63)), 0.002);
        frame.yawAngleDespun = decodeSigned(static_cast<int16_t>(readLe16(rawData + 65)), 0.002);
        frame.pitchAngleBody = decodeSigned(static_cast<int16_t>(readLe16(rawData + 67)), 0.002);
        frame.yawAngleBody = decodeSigned(static_cast<int16_t>(readLe16(rawData + 69)), 0.002);
        frame.gyroTemperature = static_cast<int8_t>(rawData[71]);
        uint16_t selfTestFlagsValue = readLe16(rawData + 72);
        frame.selfTestFlags.innerEncoderSelfTest = (selfTestFlagsValue >> 0) & ((1u << 1) - 1u);
        frame.selfTestFlags.outerEncoderSelfTest = (selfTestFlagsValue >> 1) & ((1u << 1) - 1u);
        frame.selfTestFlags.despunEncoderSelfTest = (selfTestFlagsValue >> 2) & ((1u << 1) - 1u);
        frame.selfTestFlags.gimbalGyroSelfTest = (selfTestFlagsValue >> 3) & ((1u << 1) - 1u);
        frame.selfTestFlags.insSelfTest = (selfTestFlagsValue >> 4) & ((1u << 1) - 1u);
        frame.selfTestFlags.imageSelfTest = (selfTestFlagsValue >> 5) & ((1u << 1) - 1u);
        frame.selfTestFlags.communication422SelfTest = (selfTestFlagsValue >> 6) & ((1u << 1) - 1u);
        frame.selfTestFlags.gimbalSelfTest = (selfTestFlagsValue >> 7) & ((1u << 1) - 1u);
        frame.selfTestFlags.innerEncoderHoming = (selfTestFlagsValue >> 8) & ((1u << 1) - 1u);
        frame.selfTestFlags.outerEncoderHoming = (selfTestFlagsValue >> 9) & ((1u << 1) - 1u);
        frame.selfTestFlags.despunEncoderHoming = (selfTestFlagsValue >> 10) & ((1u << 1) - 1u);
        frame.selfTestFlags.operatingSystemSelfTest = (selfTestFlagsValue >> 11) & ((1u << 1) - 1u);
        frame.selfTestFlags.imageStorageStatus = (selfTestFlagsValue >> 12) & ((1u << 1) - 1u);
        frame.selfTestFlags.reservedBits = (selfTestFlagsValue >> 13) & ((1u << 3) - 1u);
        frame.imageSelfTestStatus = static_cast<uint8_t>(rawData[74]);
        uint8_t controlStatusValue = static_cast<uint8_t>(rawData[75]);
        frame.controlStatus.gimbalControlStatus = (controlStatusValue >> 0) & ((1u << 4) - 1u);
        frame.controlStatus.despunControlStatus = (controlStatusValue >> 4) & ((1u << 4) - 1u);
        frame.targetErrorAngleX = decodeSigned(static_cast<int16_t>(readLe16(rawData + 76)), 0.1);
        frame.targetErrorAngleY = decodeSigned(static_cast<int16_t>(readLe16(rawData + 78)), 0.1);
        uint16_t imageControlValue = readLe16(rawData + 80);
        frame.imageControl.programmedGear = (imageControlValue >> 0) & ((1u << 4) - 1u);
        frame.imageControl.imageCaptureMode = (imageControlValue >> 4) & ((1u << 4) - 1u);
        frame.imageControl.losAngularVelocityAvailable = (imageControlValue >> 8) & ((1u << 1) - 1u);
        frame.imageControl.angleMeasurementAvailable = (imageControlValue >> 9) & ((1u << 1) - 1u);
        frame.imageControl.imageCalibrationStatus = (imageControlValue >> 10) & ((1u << 2) - 1u);
        frame.imageControl.reservedBits = (imageControlValue >> 12) & ((1u << 4) - 1u);
        frame.targetGrayscaleMean = readLe16(rawData + 82);
        frame.fullImageMean = readLe16(rawData + 84);
        frame.innerEncoderCommunicationError = static_cast<uint8_t>(rawData[86]);
        frame.outerEncoderCommunicationError = static_cast<uint8_t>(rawData[87]);
        frame.despunEncoderCommunicationError = static_cast<uint8_t>(rawData[88]);
        frame.gyroCommunicationError = static_cast<uint8_t>(rawData[89]);
        frame.insCommunicationError = static_cast<uint8_t>(rawData[90]);
        frame.communication422Error = static_cast<uint8_t>(rawData[91]);
        frame.imageRv1126bCommunicationError = static_cast<uint8_t>(rawData[92]);
        return true;
    }

    // Build schema metadata for valid fields.
    static MB_DDF::Tools::LogSchema buildSchema() {
        MB_DDF::Tools::LogSchema schema;
        using LFT = MB_DDF::Tools::LogFieldType;
        const uint32_t despunInsStatus_offset = offset_of_member(&Dyt_to_main_frame_b::despunInsStatus);
        const uint32_t dytStatus_offset = offset_of_member(&Dyt_to_main_frame_b::dytStatus);
        const uint32_t selfTestFlags_offset = offset_of_member(&Dyt_to_main_frame_b::selfTestFlags);
        const uint32_t controlStatus_offset = offset_of_member(&Dyt_to_main_frame_b::controlStatus);
        const uint32_t imageControl_offset = offset_of_member(&Dyt_to_main_frame_b::imageControl);
        schema.addFieldAt("B帧帧标识", LFT::UInt8, 1, offset_of_member(&Dyt_to_main_frame_b::frameIdentifier));
        schema.addFieldAt("B帧帧计数", LFT::UInt16, 1, offset_of_member(&Dyt_to_main_frame_b::frameCounter));
        schema.addFieldAt("消旋码盘滚转角度", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::despunEncoderRollAngle));
        schema.addFieldAt("消旋平台滚转角（惯测积分）", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::despunPlatformRollAngle));
        schema.addFieldAt("弹旋频率", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::spinFrequency));
        schema.addFieldAt("消旋惯测序列号", LFT::UInt8, 1, offset_of_member(&Dyt_to_main_frame_b::despunInsSequence));
        schema.addFieldAt("消旋惯测X轴角增量Δαx", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::despunInsAngleIncrementX));
        schema.addFieldAt("消旋惯测Y轴角增量Δαy", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::despunInsAngleIncrementY));
        schema.addFieldAt("消旋惯测Z轴角增量Δαz", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::despunInsAngleIncrementZ));
        schema.addFieldAt("消旋惯测X轴速度增量ΔVx", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::despunInsVelocityIncrementX));
        schema.addFieldAt("消旋惯测Y轴速度增量ΔVy", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::despunInsVelocityIncrementY));
        schema.addFieldAt("消旋惯测Z轴速度增量ΔVz", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::despunInsVelocityIncrementZ));
        schema.addFieldAt("消旋惯测X轴角速度ωx", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::despunInsAngularVelocityX));
        schema.addFieldAt("消旋惯测Y轴角速度ωy", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::despunInsAngularVelocityY));
        schema.addFieldAt("消旋惯测Z轴角速度ωz", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::despunInsAngularVelocityZ));
        schema.addFieldAt("消旋惯测X轴加速度Nx", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::despunInsAccelerationX));
        schema.addFieldAt("消旋惯测Y轴加速度Ny", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::despunInsAccelerationY));
        schema.addFieldAt("消旋惯测Z轴加速度Nz", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::despunInsAccelerationZ));
        schema.addFieldAt("消旋惯测温度T", LFT::Int8, 1, offset_of_member(&Dyt_to_main_frame_b::despunInsTemperature));
        schema.addFieldAt("消旋惯测自检分状态", LFT::UInt16, 1, offset_of_member(&Dyt_to_main_frame_b::despunInsSelfTestStatus));
        schema.addBitFieldAt("消旋惯测标定状态", LFT::UInt8, 0, 2, despunInsStatus_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("消旋惯测软件状态", LFT::UInt8, 2, 2, despunInsStatus_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("备份", LFT::UInt8, 4, 4, despunInsStatus_offset, 0, LFT::UInt8);
        schema.addFieldAt("消旋惯测软件版本号", LFT::UInt16, 1, offset_of_member(&Dyt_to_main_frame_b::despunInsSoftwareVersion));
        schema.addFieldAt("内框码盘角度（偏航）", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::innerEncoderAngleYaw));
        schema.addFieldAt("外框码盘角度（俯仰）", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::outerEncoderAnglePitch));
        schema.addFieldAt("内框视线角速度dqh（消旋）", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::innerLosAngularVelocityDespun));
        schema.addFieldAt("外框视线角速度dqv（消旋）", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::outerLosAngularVelocityDespun));
        schema.addFieldAt("内框视线角速度dqh（弹体系）", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::innerLosAngularVelocityBody));
        schema.addFieldAt("外框视线角速度dqv（弹体系）", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::outerLosAngularVelocityBody));
        schema.addBitFieldAt("DYT自检状态", LFT::UInt8, 0, 2, dytStatus_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("DYT截获状态", LFT::UInt8, 2, 2, dytStatus_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("DYT工作状态", LFT::UInt8, 4, 2, dytStatus_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("DYT工作模式回告", LFT::UInt8, 6, 2, dytStatus_offset, 0, LFT::UInt8);
        schema.addFieldAt("内框陀螺角速度", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::innerGyroAngularVelocity));
        schema.addFieldAt("外框陀螺角速度", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::outerGyroAngularVelocity));
        schema.addFieldAt("内框电机电压", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::innerMotorVoltage));
        schema.addFieldAt("外框电机电压", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::outerMotorVoltage));
        schema.addFieldAt("消旋电机电压", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::despunMotorVoltage));
        schema.addFieldAt("俯仰测角（消旋系）", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::pitchAngleDespun));
        schema.addFieldAt("偏航测角（消旋系）", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::yawAngleDespun));
        schema.addFieldAt("俯仰测角（弹体系）", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::pitchAngleBody));
        schema.addFieldAt("偏航测角（弹体系）", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::yawAngleBody));
        schema.addFieldAt("陀螺温度", LFT::Int8, 1, offset_of_member(&Dyt_to_main_frame_b::gyroTemperature));
        schema.addBitFieldAt("内框码盘自检状态", LFT::UInt16, 0, 1, selfTestFlags_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("外框码盘自检状态", LFT::UInt16, 1, 1, selfTestFlags_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("消旋码盘自检状态", LFT::UInt16, 2, 1, selfTestFlags_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("框架陀螺自检状态", LFT::UInt16, 3, 1, selfTestFlags_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("惯组自检状态", LFT::UInt16, 4, 1, selfTestFlags_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("图像自检状态", LFT::UInt16, 5, 1, selfTestFlags_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("422通讯自检状态", LFT::UInt16, 6, 1, selfTestFlags_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("框架自检状态", LFT::UInt16, 7, 1, selfTestFlags_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("内框码盘寻零状态", LFT::UInt16, 8, 1, selfTestFlags_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("外框码盘寻零状态", LFT::UInt16, 9, 1, selfTestFlags_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("消旋码盘寻零状态", LFT::UInt16, 10, 1, selfTestFlags_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("操作系统自检", LFT::UInt16, 11, 1, selfTestFlags_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("图像存储状态", LFT::UInt16, 12, 1, selfTestFlags_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("备份", LFT::UInt16, 13, 3, selfTestFlags_offset, 0, LFT::UInt8);
        schema.addFieldAt("图像自检状态", LFT::UInt8, 1, offset_of_member(&Dyt_to_main_frame_b::imageSelfTestStatus));
        schema.addBitFieldAt("框架控制状态", LFT::UInt8, 0, 4, controlStatus_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("消旋控制状态", LFT::UInt8, 4, 4, controlStatus_offset, 0, LFT::UInt8);
        schema.addFieldAt("目标误差角ΔX", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::targetErrorAngleX));
        schema.addFieldAt("目标误差角ΔY", LFT::Float64, 1, offset_of_member(&Dyt_to_main_frame_b::targetErrorAngleY));
        schema.addBitFieldAt("程控档位", LFT::UInt16, 0, 4, imageControl_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("图像截获模式", LFT::UInt16, 4, 4, imageControl_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("视线角速度可用状态", LFT::UInt16, 8, 1, imageControl_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("测角可用状态", LFT::UInt16, 9, 1, imageControl_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("图像校正状态", LFT::UInt16, 10, 2, imageControl_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("备份", LFT::UInt16, 12, 4, imageControl_offset, 0, LFT::UInt8);
        schema.addFieldAt("目标灰度均值", LFT::UInt16, 1, offset_of_member(&Dyt_to_main_frame_b::targetGrayscaleMean));
        schema.addFieldAt("全图均值", LFT::UInt16, 1, offset_of_member(&Dyt_to_main_frame_b::fullImageMean));
        schema.addFieldAt("内框码盘通讯误码", LFT::UInt8, 1, offset_of_member(&Dyt_to_main_frame_b::innerEncoderCommunicationError));
        schema.addFieldAt("外框码盘通讯误码", LFT::UInt8, 1, offset_of_member(&Dyt_to_main_frame_b::outerEncoderCommunicationError));
        schema.addFieldAt("消旋码盘通讯误码", LFT::UInt8, 1, offset_of_member(&Dyt_to_main_frame_b::despunEncoderCommunicationError));
        schema.addFieldAt("陀螺通讯误码", LFT::UInt8, 1, offset_of_member(&Dyt_to_main_frame_b::gyroCommunicationError));
        schema.addFieldAt("惯组通讯误码", LFT::UInt8, 1, offset_of_member(&Dyt_to_main_frame_b::insCommunicationError));
        schema.addFieldAt("422通讯误码", LFT::UInt8, 1, offset_of_member(&Dyt_to_main_frame_b::communication422Error));
        schema.addFieldAt("图像RV1126B通讯误码", LFT::UInt8, 1, offset_of_member(&Dyt_to_main_frame_b::imageRv1126bCommunicationError));
        return schema;
    }
};

} // namespace ProtocolModel