#pragma once
// Auto-generated by the Protocol Modeling tool. Do not edit manually.
#include <array>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include "MB_DDF/Tools/SelfDescribingLog.h"

namespace ProtocolModel {

struct Main_to_dyt_frame_a {
    struct ControlCommands {
        uint16_t dytControlCommand : 4; // DYT控制指令
        uint16_t thermalBatteryActivationCommand : 2; // 热电池激活令
        uint16_t launchSiteMotionSignal : 2; // 弹动信号（发射地）
        uint16_t dytOperatingMode : 2; // DYT工作模式（系统装订）
        uint16_t imageStorageCommand : 2; // 图像存储指令（系统装订）
        uint16_t imageCalibrationCommand : 2; // 图像校正指令（系统装订）
        uint16_t testCommand : 2; // 测试指令
    };
    struct SystemCommands {
        uint8_t despunUnlockCommand : 2; // 消旋解锁指令（系统装订）
        uint8_t dytSelfTestUpgradeCommand : 4; // DYT自检/软件升级令（系统装订）
        uint8_t reservedBits : 2; // 备份
    };
    uint8_t frameHeaderLow; // A帧帧头低字节 / 非解析字段
    uint8_t frameHeaderHigh; // A帧帧头高字节 / 非解析字段
    uint8_t frameLength; // A帧帧长 / 非解析字段
    uint8_t frameIdentifier; // A帧帧标识
    uint16_t frameCounter; // A帧帧计数
    double presetTargetPitchBody; // 预装目标俯仰指向角（弹体系）
    double presetTargetYawBody; // 预装目标偏航指向角（弹体系）
    double presetTargetPitchDespun; // 预装目标俯仰指向角（消旋系）
    double presetTargetYawDespun; // 预装目标偏航指向角（消旋系）
    double despunLockAngle; // 消旋锁定角度
    double flightTimeAfterLaunch; // 弹动后飞行时间t
    double missileVelocityX; // 导弹速度Vx
    double missileVelocityY; // 导弹速度Vy
    double missileVelocityZ; // 导弹速度Vz
    double missileTargetRelativeDistance; // 弹目相对距离
    std::array<uint8_t, 2> reserved26_27{}; // 备份
    std::array<uint8_t, 2> reserved28_29{}; // 备份
    double missilePitch; // 导弹俯仰角
    double missileYaw; // 导弹偏航角
    double missileRoll; // 导弹滚转角
    double missileLongitude; // 导弹经度
    double missileLatitude; // 导弹纬度
    double missileAltitude; // 导弹海拔高度
    uint8_t year; // 年
    uint8_t month; // 月
    uint8_t day; // 日
    uint8_t hour; // 时
    uint8_t minute; // 分
    std::array<uint8_t, 2> reserved51_52{}; // 备份
    std::array<uint8_t, 2> reserved53_54{}; // 备份
    std::array<uint8_t, 2> reserved55_56{}; // 备份
    ControlCommands controlCommands;
    uint8_t despunInsWorkCommand; // 消旋惯测工作指令（系统装订）
    SystemCommands systemCommands;
    std::array<uint8_t, 37> reserved61_97{}; // 备份
    uint16_t checksum; // 校验值 / 非解析字段

    // Initialize fields with default values.
    Main_to_dyt_frame_a() {
        frameHeaderLow = 170;
        frameHeaderHigh = 85;
        frameLength = 95;
        frameIdentifier = 160;
        frameCounter = 0;
        presetTargetPitchBody = 0;
        presetTargetYawBody = 0;
        presetTargetPitchDespun = 0;
        presetTargetYawDespun = 0;
        despunLockAngle = 0;
        flightTimeAfterLaunch = 0;
        missileVelocityX = 0;
        missileVelocityY = 0;
        missileVelocityZ = 0;
        missileTargetRelativeDistance = 0;
        missilePitch = 0;
        missileYaw = 0;
        missileRoll = 0;
        missileLongitude = 0;
        missileLatitude = 0;
        missileAltitude = 0;
        year = 0;
        month = 0;
        day = 0;
        hour = 0;
        minute = 0;
        controlCommands.dytControlCommand = 1;
        controlCommands.thermalBatteryActivationCommand = 0;
        controlCommands.launchSiteMotionSignal = 0;
        controlCommands.dytOperatingMode = 0;
        controlCommands.imageStorageCommand = 0;
        controlCommands.imageCalibrationCommand = 0;
        controlCommands.testCommand = 0;
        despunInsWorkCommand = 0;
        systemCommands.despunUnlockCommand = 1;
        systemCommands.dytSelfTestUpgradeCommand = 3;
        systemCommands.reservedBits = 0;
        checksum = 0;
    }
};

class Main_to_dyt_frame_aProtocol {
public:
    constexpr static size_t FRAME_SIZE = 95;

    // Return byte offset of a member within the frame struct.
    template<typename T, typename Member>
    constexpr static uint32_t offset_of_member(Member T::*member_ptr) {
        return static_cast<uint32_t>(
            reinterpret_cast<uintptr_t>(
                &(static_cast<T*>(nullptr)->*member_ptr)
            )
        );
    }

    // Write 16-bit unsigned integer in little-endian.
    static inline void writeLe16(char* dst, uint16_t value) {
        dst[0] = static_cast<char>(value & 0xFF);
        dst[1] = static_cast<char>((value >> 8) & 0xFF);
    }

    // Write 32-bit unsigned integer in little-endian.
    static inline void writeLe32(char* dst, uint32_t value) {
        dst[0] = static_cast<char>(value & 0xFF);
        dst[1] = static_cast<char>((value >> 8) & 0xFF);
        dst[2] = static_cast<char>((value >> 16) & 0xFF);
        dst[3] = static_cast<char>((value >> 24) & 0xFF);
    }

    // Read 16-bit unsigned integer in little-endian.
    static inline uint16_t readLe16(const char* src) {
        return static_cast<uint8_t>(src[0]) | (static_cast<uint8_t>(src[1]) << 8);
    }

    // Read 32-bit unsigned integer in little-endian.
    static inline uint32_t readLe32(const char* src) {
        return static_cast<uint8_t>(src[0]) | (static_cast<uint8_t>(src[1]) << 8)
            | (static_cast<uint8_t>(src[2]) << 16) | (static_cast<uint8_t>(src[3]) << 24);
    }

    // Encode unsigned value with LSB scaling.
    static inline uint32_t encodeUnsigned(double actual, double lsb) {
        return static_cast<uint32_t>(actual / lsb);
    }

    // Encode signed value with LSB scaling.
    static inline int32_t encodeSigned(double actual, double lsb) {
        return static_cast<int32_t>(actual / lsb);
    }

    // Decode unsigned value with LSB scaling.
    static inline double decodeUnsigned(uint32_t encoded, double lsb) {
        return static_cast<double>(encoded) * lsb;
    }

    // Decode signed value with LSB scaling.
    static inline double decodeSigned(int32_t encoded, double lsb) {
        return static_cast<double>(encoded) * lsb;
    }

    // Pack valid fields into a byte buffer.
    static std::array<char, FRAME_SIZE> packFrame(const Main_to_dyt_frame_a& frame) {
        std::array<char, FRAME_SIZE> buffer{};
        buffer[0] = static_cast<char>(frame.frameIdentifier);
        writeLe16(buffer.data() + 1, static_cast<uint16_t>(frame.frameCounter));
        writeLe16(buffer.data() + 3, static_cast<uint16_t>(encodeSigned(frame.presetTargetPitchBody, 0.002)));
        writeLe16(buffer.data() + 5, static_cast<uint16_t>(encodeSigned(frame.presetTargetYawBody, 0.002)));
        writeLe16(buffer.data() + 7, static_cast<uint16_t>(encodeSigned(frame.presetTargetPitchDespun, 0.002)));
        writeLe16(buffer.data() + 9, static_cast<uint16_t>(encodeSigned(frame.presetTargetYawDespun, 0.002)));
        writeLe16(buffer.data() + 11, static_cast<uint16_t>(encodeUnsigned(frame.despunLockAngle, 0.0055)));
        writeLe16(buffer.data() + 13, static_cast<uint16_t>(encodeUnsigned(frame.flightTimeAfterLaunch, 0.0025)));
        writeLe16(buffer.data() + 15, static_cast<uint16_t>(encodeSigned(frame.missileVelocityX, 0.05)));
        writeLe16(buffer.data() + 17, static_cast<uint16_t>(encodeSigned(frame.missileVelocityY, 0.05)));
        writeLe16(buffer.data() + 19, static_cast<uint16_t>(encodeSigned(frame.missileVelocityZ, 0.05)));
        writeLe16(buffer.data() + 21, static_cast<uint16_t>(encodeUnsigned(frame.missileTargetRelativeDistance, 0.3)));
        writeLe16(buffer.data() + 27, static_cast<uint16_t>(encodeSigned(frame.missilePitch, 0.01)));
        writeLe16(buffer.data() + 29, static_cast<uint16_t>(encodeSigned(frame.missileYaw, 0.01)));
        writeLe16(buffer.data() + 31, static_cast<uint16_t>(encodeSigned(frame.missileRoll, 0.0055)));
        writeLe32(buffer.data() + 33, static_cast<uint32_t>(encodeSigned(frame.missileLongitude, 1e-07)));
        writeLe32(buffer.data() + 37, static_cast<uint32_t>(encodeSigned(frame.missileLatitude, 5e-08)));
        writeLe16(buffer.data() + 41, static_cast<uint16_t>(encodeUnsigned(frame.missileAltitude, 0.5)));
        buffer[43] = static_cast<char>(frame.year);
        buffer[44] = static_cast<char>(frame.month);
        buffer[45] = static_cast<char>(frame.day);
        buffer[46] = static_cast<char>(frame.hour);
        buffer[47] = static_cast<char>(frame.minute);
        uint16_t controlCommandsValue = 0;
        controlCommandsValue |= (static_cast<uint16_t>(frame.controlCommands.dytControlCommand) & ((1u << 4) - 1u)) << 0;
        controlCommandsValue |= (static_cast<uint16_t>(frame.controlCommands.thermalBatteryActivationCommand) & ((1u << 2) - 1u)) << 4;
        controlCommandsValue |= (static_cast<uint16_t>(frame.controlCommands.launchSiteMotionSignal) & ((1u << 2) - 1u)) << 6;
        controlCommandsValue |= (static_cast<uint16_t>(frame.controlCommands.dytOperatingMode) & ((1u << 2) - 1u)) << 8;
        controlCommandsValue |= (static_cast<uint16_t>(frame.controlCommands.imageStorageCommand) & ((1u << 2) - 1u)) << 10;
        controlCommandsValue |= (static_cast<uint16_t>(frame.controlCommands.imageCalibrationCommand) & ((1u << 2) - 1u)) << 12;
        controlCommandsValue |= (static_cast<uint16_t>(frame.controlCommands.testCommand) & ((1u << 2) - 1u)) << 14;
        writeLe16(buffer.data() + 54, controlCommandsValue);
        buffer[56] = static_cast<char>(frame.despunInsWorkCommand);
        uint8_t systemCommandsValue = 0;
        systemCommandsValue |= (static_cast<uint8_t>(frame.systemCommands.despunUnlockCommand) & ((1u << 2) - 1u)) << 0;
        systemCommandsValue |= (static_cast<uint8_t>(frame.systemCommands.dytSelfTestUpgradeCommand) & ((1u << 4) - 1u)) << 2;
        systemCommandsValue |= (static_cast<uint8_t>(frame.systemCommands.reservedBits) & ((1u << 2) - 1u)) << 6;
        buffer[57] = static_cast<char>(systemCommandsValue);
        return buffer;
    }

    // Unpack valid fields from a byte buffer.
    static bool unpackFrame(const char* rawData, size_t dataSize, Main_to_dyt_frame_a& frame) {
        if ((!rawData) || (dataSize < FRAME_SIZE)) {
            return false;
        }
        frame.frameIdentifier = static_cast<uint8_t>(rawData[0]);
        frame.frameCounter = readLe16(rawData + 1);
        frame.presetTargetPitchBody = decodeSigned(static_cast<int16_t>(readLe16(rawData + 3)), 0.002);
        frame.presetTargetYawBody = decodeSigned(static_cast<int16_t>(readLe16(rawData + 5)), 0.002);
        frame.presetTargetPitchDespun = decodeSigned(static_cast<int16_t>(readLe16(rawData + 7)), 0.002);
        frame.presetTargetYawDespun = decodeSigned(static_cast<int16_t>(readLe16(rawData + 9)), 0.002);
        frame.despunLockAngle = decodeUnsigned(readLe16(rawData + 11), 0.0055);
        frame.flightTimeAfterLaunch = decodeUnsigned(readLe16(rawData + 13), 0.0025);
        frame.missileVelocityX = decodeSigned(static_cast<int16_t>(readLe16(rawData + 15)), 0.05);
        frame.missileVelocityY = decodeSigned(static_cast<int16_t>(readLe16(rawData + 17)), 0.05);
        frame.missileVelocityZ = decodeSigned(static_cast<int16_t>(readLe16(rawData + 19)), 0.05);
        frame.missileTargetRelativeDistance = decodeUnsigned(readLe16(rawData + 21), 0.3);
        frame.missilePitch = decodeSigned(static_cast<int16_t>(readLe16(rawData + 27)), 0.01);
        frame.missileYaw = decodeSigned(static_cast<int16_t>(readLe16(rawData + 29)), 0.01);
        frame.missileRoll = decodeSigned(static_cast<int16_t>(readLe16(rawData + 31)), 0.0055);
        frame.missileLongitude = decodeSigned(static_cast<int32_t>(readLe32(rawData + 33)), 1e-07);
        frame.missileLatitude = decodeSigned(static_cast<int32_t>(readLe32(rawData + 37)), 5e-08);
        frame.missileAltitude = decodeUnsigned(readLe16(rawData + 41), 0.5);
        frame.year = static_cast<uint8_t>(rawData[43]);
        frame.month = static_cast<uint8_t>(rawData[44]);
        frame.day = static_cast<uint8_t>(rawData[45]);
        frame.hour = static_cast<uint8_t>(rawData[46]);
        frame.minute = static_cast<uint8_t>(rawData[47]);
        uint16_t controlCommandsValue = readLe16(rawData + 54);
        frame.controlCommands.dytControlCommand = (controlCommandsValue >> 0) & ((1u << 4) - 1u);
        frame.controlCommands.thermalBatteryActivationCommand = (controlCommandsValue >> 4) & ((1u << 2) - 1u);
        frame.controlCommands.launchSiteMotionSignal = (controlCommandsValue >> 6) & ((1u << 2) - 1u);
        frame.controlCommands.dytOperatingMode = (controlCommandsValue >> 8) & ((1u << 2) - 1u);
        frame.controlCommands.imageStorageCommand = (controlCommandsValue >> 10) & ((1u << 2) - 1u);
        frame.controlCommands.imageCalibrationCommand = (controlCommandsValue >> 12) & ((1u << 2) - 1u);
        frame.controlCommands.testCommand = (controlCommandsValue >> 14) & ((1u << 2) - 1u);
        frame.despunInsWorkCommand = static_cast<uint8_t>(rawData[56]);
        uint8_t systemCommandsValue = static_cast<uint8_t>(rawData[57]);
        frame.systemCommands.despunUnlockCommand = (systemCommandsValue >> 0) & ((1u << 2) - 1u);
        frame.systemCommands.dytSelfTestUpgradeCommand = (systemCommandsValue >> 2) & ((1u << 4) - 1u);
        frame.systemCommands.reservedBits = (systemCommandsValue >> 6) & ((1u << 2) - 1u);
        return true;
    }

    // Build schema metadata for valid fields.
    static MB_DDF::Tools::LogSchema buildSchema() {
        MB_DDF::Tools::LogSchema schema;
        using LFT = MB_DDF::Tools::LogFieldType;
        const uint32_t controlCommands_offset = offset_of_member(&Main_to_dyt_frame_a::controlCommands);
        const uint32_t systemCommands_offset = offset_of_member(&Main_to_dyt_frame_a::systemCommands);
        schema.addFieldAt("A帧帧标识", LFT::UInt8, 1, offset_of_member(&Main_to_dyt_frame_a::frameIdentifier));
        schema.addFieldAt("A帧帧计数", LFT::UInt16, 1, offset_of_member(&Main_to_dyt_frame_a::frameCounter));
        schema.addFieldAt("预装目标俯仰指向角（弹体系）", LFT::Float64, 1, offset_of_member(&Main_to_dyt_frame_a::presetTargetPitchBody));
        schema.addFieldAt("预装目标偏航指向角（弹体系）", LFT::Float64, 1, offset_of_member(&Main_to_dyt_frame_a::presetTargetYawBody));
        schema.addFieldAt("预装目标俯仰指向角（消旋系）", LFT::Float64, 1, offset_of_member(&Main_to_dyt_frame_a::presetTargetPitchDespun));
        schema.addFieldAt("预装目标偏航指向角（消旋系）", LFT::Float64, 1, offset_of_member(&Main_to_dyt_frame_a::presetTargetYawDespun));
        schema.addFieldAt("消旋锁定角度", LFT::Float64, 1, offset_of_member(&Main_to_dyt_frame_a::despunLockAngle));
        schema.addFieldAt("弹动后飞行时间t", LFT::Float64, 1, offset_of_member(&Main_to_dyt_frame_a::flightTimeAfterLaunch));
        schema.addFieldAt("导弹速度Vx", LFT::Float64, 1, offset_of_member(&Main_to_dyt_frame_a::missileVelocityX));
        schema.addFieldAt("导弹速度Vy", LFT::Float64, 1, offset_of_member(&Main_to_dyt_frame_a::missileVelocityY));
        schema.addFieldAt("导弹速度Vz", LFT::Float64, 1, offset_of_member(&Main_to_dyt_frame_a::missileVelocityZ));
        schema.addFieldAt("弹目相对距离", LFT::Float64, 1, offset_of_member(&Main_to_dyt_frame_a::missileTargetRelativeDistance));
        schema.addFieldAt("导弹俯仰角", LFT::Float64, 1, offset_of_member(&Main_to_dyt_frame_a::missilePitch));
        schema.addFieldAt("导弹偏航角", LFT::Float64, 1, offset_of_member(&Main_to_dyt_frame_a::missileYaw));
        schema.addFieldAt("导弹滚转角", LFT::Float64, 1, offset_of_member(&Main_to_dyt_frame_a::missileRoll));
        schema.addFieldAt("导弹经度", LFT::Float64, 1, offset_of_member(&Main_to_dyt_frame_a::missileLongitude));
        schema.addFieldAt("导弹纬度", LFT::Float64, 1, offset_of_member(&Main_to_dyt_frame_a::missileLatitude));
        schema.addFieldAt("导弹海拔高度", LFT::Float64, 1, offset_of_member(&Main_to_dyt_frame_a::missileAltitude));
        schema.addFieldAt("年", LFT::UInt8, 1, offset_of_member(&Main_to_dyt_frame_a::year));
        schema.addFieldAt("月", LFT::UInt8, 1, offset_of_member(&Main_to_dyt_frame_a::month));
        schema.addFieldAt("日", LFT::UInt8, 1, offset_of_member(&Main_to_dyt_frame_a::day));
        schema.addFieldAt("时", LFT::UInt8, 1, offset_of_member(&Main_to_dyt_frame_a::hour));
        schema.addFieldAt("分", LFT::UInt8, 1, offset_of_member(&Main_to_dyt_frame_a::minute));
        schema.addBitFieldAt("DYT控制指令", LFT::UInt16, 0, 4, controlCommands_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("热电池激活令", LFT::UInt16, 4, 2, controlCommands_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("弹动信号（发射地）", LFT::UInt16, 6, 2, controlCommands_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("DYT工作模式（系统装订）", LFT::UInt16, 8, 2, controlCommands_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("图像存储指令（系统装订）", LFT::UInt16, 10, 2, controlCommands_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("图像校正指令（系统装订）", LFT::UInt16, 12, 2, controlCommands_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("测试指令", LFT::UInt16, 14, 2, controlCommands_offset, 0, LFT::UInt8);
        schema.addFieldAt("消旋惯测工作指令（系统装订）", LFT::UInt8, 1, offset_of_member(&Main_to_dyt_frame_a::despunInsWorkCommand));
        schema.addBitFieldAt("消旋解锁指令（系统装订）", LFT::UInt8, 0, 2, systemCommands_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("DYT自检/软件升级令（系统装订）", LFT::UInt8, 2, 4, systemCommands_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("备份", LFT::UInt8, 6, 2, systemCommands_offset, 0, LFT::UInt8);
        return schema;
    }
};

} // namespace ProtocolModel